version: "3.8"
services:

  kibana:
    image: kibana:7.9.1
    container_name: kibana
    restart: always
    volumes:
      - type: bind
        source: ./ConfFiles/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    depends_on:
      - elst

  elst:
    image: elasticsearch:7.9.1
    container_name: elasticsearch
    restart: always
    volumes:
      - type: bind
        source: ./ConfFiles/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
    ports:
      - "9200:9200/tcp"
      - "9300:9300/tcp"
      - "9200:9200/udp"
      - "9300:9300/udp"

  log:
    image: logstash:7.9.1
    container_name: log
    restart: always
    volumes:
      - type: bind
        source: ./ConfFiles/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./ConfFiles/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    depends_on:
      - kibana
      - elst
