version: "3.8"
services:
  kibana:
    build:
      context: ./dir
      dockerfile: nginxdockerfile
    container_name: nginx
    restart: always
    volumes:
      - type: bind
        source: ./filebeat.yml
        target: /etc/filebeat/filebeat.yml
        read_only: true
      - type: bind
        source: ./metricbeat.yml
        target: /etc/metricbeat/metricbeat.yml
        read_only: true
    ports:
      - "5601:5601"
      - "9200:9200"
