filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
- type: syslog
  enabled: true
  paths:
    - /var/log/secure
    - /var/log/messages

filebeat.modules:
- module: nginx
  enabled: true
- module: system
  enabled: true

setup.template.settings:
  index.number_of_shards: 1

setup.dashboards.enabled: true

setup.kibana:
  host: "192.168.0.87:5601"

#output.elasticsearch:
 # hosts: ["localhost:9200"]

output.logstash:
  hosts: ["192.168.0.87:5044"]
  enabled: true
