filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
- type: log
  paths:
    - /var/log/nginx/*.log
  tags: ["nginx"]

filebeat.modules:
- module: nginx
  enabled: true

- module: system
  syslog:
    enabled: true
    var.paths: ["/var/log/messages*"]
  auth:
    enabled: true
    var.paths: ["/var/log/secure*"]

setup.dashboards.enabled: true
setup.kibana.host: "192.168.0.89:5601"
setup.kibana.username: elastic
setup.kibana.password: changeme

#output.elasticsearch:
#  hosts: ["192.168.0.89:9200"]
#  enabled: true
#  username: "elastic"
#  password: "changeme"

output.logstash:
  hosts: ["192.168.0.89:5044"]
  enabled: true
