filebeat.inputs:
- type: syslog
  enabled: true
  paths:
    - /var/log/*.log
- type: nginx
  enabled: true
  paths:
    - /var/log/nginx/*.log

filebeat.modules:
- module: nginx
  enabled: true

- module: system
  enabled: true

- module: logstash
  enabled: true

setup.dashboards.enabled: true
setup.kibana.host: "192.168.0.89:5601"
setup.kibana.username: elastic
setup.kibana.password: changeme

#output.elasticsearch:
 # hosts: ["localhost:9200"]

output.logstash:
  hosts: ["192.168.0.89:5044"]
  enabled: true
