metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.period: 10s
  reload.enabled: false

metricbeat.modules:
- module: nginx
  hosts: ["127.0.0.1"]
  enabled: true

- module: system
  enabled: true

- module: elasticsearch
  enabled: true

- module: logstash
  enabled: true

timeseries.enabled: true

setup.dashboards.enabled: true
setup.dashboards.retry.enabled: true

setup.kibana.host: "192.168.0.89:5601"
setup.kibana.username: elastic
setup.kibana.password: changeme
#output.elasticsearch:
#  hosts: ["192.168.0.87:9200"]

output.logstash:
  hosts: ["192.168.0.89:5044"]
  enabled: true
